//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool (tools/generate_strings.py or Visual Studio).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. Edit Strings.resx instead.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintVect.App {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintVect.App.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PrintVect.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Collecting information about this PC, please wait....
        /// </summary>
        internal static string DiagCollecting {
            get {
                return ResourceManager.GetString("DiagCollecting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copied. You can now paste it into an email or chat..
        /// </summary>
        internal static string DiagCopied {
            get {
                return ResourceManager.GetString("DiagCopied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string DiagCopy {
            get {
                return ResourceManager.GetString("DiagCopy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not copy to the clipboard. Select the text with the mouse and press Ctrl+C instead..
        /// </summary>
        internal static string DiagCopyFailed {
            get {
                return ResourceManager.GetString("DiagCopyFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (default).
        /// </summary>
        internal static string DiagDefaultPrinterSuffix {
            get {
                return ResourceManager.GetString("DiagDefaultPrinterSuffix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not collect the information: {0}.
        /// </summary>
        internal static string DiagFailed {
            get {
                return ResourceManager.GetString("DiagFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If printing does not work, press "Copy to clipboard" and paste the text into an email or chat to the [rest of string was truncated].
        /// </summary>
        internal static string DiagIntro {
            get {
                return ResourceManager.GetString("DiagIntro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No printers are installed on this PC..
        /// </summary>
        internal static string DiagNoPrinters {
            get {
                return ResourceManager.GetString("DiagNoPrinters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open log folder.
        /// </summary>
        internal static string DiagOpenLogs {
            get {
                return ResourceManager.GetString("DiagOpenLogs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not open the log folder. It is here: {0}.
        /// </summary>
        internal static string DiagOpenLogsFailed {
            get {
                return ResourceManager.GetString("DiagOpenLogsFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not read the printer list: {0}.
        /// </summary>
        internal static string DiagPrintersError {
            get {
                return ResourceManager.GetString("DiagPrintersError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Printers on this PC.
        /// </summary>
        internal static string DiagPrintersSection {
            get {
                return ResourceManager.GetString("DiagPrintersSection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string DiagRefresh {
            get {
                return ResourceManager.GetString("DiagRefresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to not set (open to the office network).
        /// </summary>
        internal static string PinNotSet {
            get {
                return ResourceManager.GetString("PinNotSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to set.
        /// </summary>
        internal static string PinSet {
            get {
                return ResourceManager.GetString("PinSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings file: {0}.
        /// </summary>
        internal static string SettingsConfigFile {
            get {
                return ResourceManager.GetString("SettingsConfigFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to These settings are read from the file shown below. Changing them from this screen comes in a later u [rest of string was truncated].
        /// </summary>
        internal static string SettingsIntro {
            get {
                return ResourceManager.GetString("SettingsIntro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keep sent files for: {0} hour(s).
        /// </summary>
        internal static string SettingsKeepFiles {
            get {
                return ResourceManager.GetString("SettingsKeepFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shared PIN: {0}.
        /// </summary>
        internal static string SettingsPin {
            get {
                return ResourceManager.GetString("SettingsPin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Discovery port (UDP): {0}     Job port (TCP): {1}.
        /// </summary>
        internal static string SettingsPorts {
            get {
                return ResourceManager.GetString("SettingsPorts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sharing my printers: {0}.
        /// </summary>
        internal static string SettingsSharing {
            get {
                return ResourceManager.GetString("SettingsSharing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start with Windows: {0}.
        /// </summary>
        internal static string SettingsStartWithWindows {
            get {
                return ResourceManager.GetString("SettingsStartWithWindows", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This part is not ready yet. It will list the printers connected to this PC so you can share them wit [rest of string was truncated].
        /// </summary>
        internal static string SharePlaceholder {
            get {
                return ResourceManager.GetString("SharePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PrintVect could not create its data folder: {0}  {1}  Ask the person who installed PrintVect to chec [rest of string was truncated].
        /// </summary>
        internal static string StartupFolderError {
            get {
                return ResourceManager.GetString("StartupFolderError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sharing is OFF.
        /// </summary>
        internal static string StatusSharingOff {
            get {
                return ResourceManager.GetString("StatusSharingOff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sharing is ON.
        /// </summary>
        internal static string StatusSharingOn {
            get {
                return ResourceManager.GetString("StatusSharingOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string StatusVersion {
            get {
                return ResourceManager.GetString("StatusVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        internal static string TabDiagnostics {
            get {
                return ResourceManager.GetString("TabDiagnostics", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share my printers.
        /// </summary>
        internal static string TabShare {
            get {
                return ResourceManager.GetString("TabShare", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use shared printers.
        /// </summary>
        internal static string TabUse {
            get {
                return ResourceManager.GetString("TabUse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string TrayExit {
            get {
                return ResourceManager.GetString("TrayExit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open PrintVect.
        /// </summary>
        internal static string TrayOpen {
            get {
                return ResourceManager.GetString("TrayOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PrintVect keeps running in the tray so that printing keeps working. To close it completely, right-cl [rest of string was truncated].
        /// </summary>
        internal static string TrayStillRunningText {
            get {
                return ResourceManager.GetString("TrayStillRunningText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PrintVect is still running.
        /// </summary>
        internal static string TrayStillRunningTitle {
            get {
                return ResourceManager.GetString("TrayStillRunningTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Something went wrong inside PrintVect. The details have been written to the log file. If it happens  [rest of string was truncated].
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This part is not ready yet. It will show the printers shared by other PCs in the office so you can a [rest of string was truncated].
        /// </summary>
        internal static string UsePlaceholder {
            get {
                return ResourceManager.GetString("UsePlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
