//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool (tools/generate_strings.py or Visual Studio).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. Edit Strings.resx instead.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintVect.App {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintVect.App.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PrintVect.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "{0}" was not printed: {1}.
        /// </summary>
        internal static string BalloonClientFailed {
            get {
                return ResourceManager.GetString("BalloonClientFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "{0}" is waiting: {1}.
        /// </summary>
        internal static string BalloonClientPending {
            get {
                return ResourceManager.GetString("BalloonClientPending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "{0}" printed on {1}..
        /// </summary>
        internal static string BalloonClientPrinted {
            get {
                return ResourceManager.GetString("BalloonClientPrinted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PrintVect printers need attention.
        /// </summary>
        internal static string BalloonClientStartFailedTitle {
            get {
                return ResourceManager.GetString("BalloonClientStartFailedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not print "{0}" from {1}: {2}.
        /// </summary>
        internal static string BalloonJobFailed {
            get {
                return ResourceManager.GetString("BalloonJobFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Printed "{0}" from {1} on {2}.
        /// </summary>
        internal static string BalloonJobPrinted {
            get {
                return ResourceManager.GetString("BalloonJobPrinted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Printing "{0}" from {1} on {2}.
        /// </summary>
        internal static string BalloonJobReceived {
            get {
                return ResourceManager.GetString("BalloonJobReceived", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Printer sharing did not start.
        /// </summary>
        internal static string BalloonSharingFailedTitle {
            get {
                return ResourceManager.GetString("BalloonSharingFailedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Printers from other PCs (client role).
        /// </summary>
        internal static string DiagClientSection {
            get {
                return ResourceManager.GetString("DiagClientSection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Collecting information about this PC, please wait....
        /// </summary>
        internal static string DiagCollecting {
            get {
                return ResourceManager.GetString("DiagCollecting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copied. You can now paste it into an email or chat..
        /// </summary>
        internal static string DiagCopied {
            get {
                return ResourceManager.GetString("DiagCopied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string DiagCopy {
            get {
                return ResourceManager.GetString("DiagCopy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not copy to the clipboard. Select the text with the mouse and press Ctrl+C instead..
        /// </summary>
        internal static string DiagCopyFailed {
            get {
                return ResourceManager.GetString("DiagCopyFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (default).
        /// </summary>
        internal static string DiagDefaultPrinterSuffix {
            get {
                return ResourceManager.GetString("DiagDefaultPrinterSuffix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not collect the information: {0}.
        /// </summary>
        internal static string DiagFailed {
            get {
                return ResourceManager.GetString("DiagFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Printer sharing (host role).
        /// </summary>
        internal static string DiagHostSection {
            get {
                return ResourceManager.GetString("DiagHostSection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If printing does not work, press "Copy to clipboard" and paste the text into an email or chat to the [rest of string was truncated].
        /// </summary>
        internal static string DiagIntro {
            get {
                return ResourceManager.GetString("DiagIntro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No printers are installed on this PC..
        /// </summary>
        internal static string DiagNoPrinters {
            get {
                return ResourceManager.GetString("DiagNoPrinters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open log folder.
        /// </summary>
        internal static string DiagOpenLogs {
            get {
                return ResourceManager.GetString("DiagOpenLogs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not open the log folder. It is here: {0}.
        /// </summary>
        internal static string DiagOpenLogsFailed {
            get {
                return ResourceManager.GetString("DiagOpenLogsFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not read the printer list: {0}.
        /// </summary>
        internal static string DiagPrintersError {
            get {
                return ResourceManager.GetString("DiagPrintersError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Printers on this PC.
        /// </summary>
        internal static string DiagPrintersSection {
            get {
                return ResourceManager.GetString("DiagPrintersSection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string DiagRefresh {
            get {
                return ResourceManager.GetString("DiagRefresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string JobColDocument {
            get {
                return ResourceManager.GetString("JobColDocument", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string JobColFrom {
            get {
                return ResourceManager.GetString("JobColFrom", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Host PC.
        /// </summary>
        internal static string JobColHost {
            get {
                return ResourceManager.GetString("JobColHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string JobColMessage {
            get {
                return ResourceManager.GetString("JobColMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        internal static string JobColPrinter {
            get {
                return ResourceManager.GetString("JobColPrinter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string JobColState {
            get {
                return ResourceManager.GetString("JobColState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string JobColTime {
            get {
                return ResourceManager.GetString("JobColTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string JobState_error {
            get {
                return ResourceManager.GetString("JobState_error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string JobState_pending {
            get {
                return ResourceManager.GetString("JobState_pending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Printed.
        /// </summary>
        internal static string JobState_printed {
            get {
                return ResourceManager.GetString("JobState_printed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Printing.
        /// </summary>
        internal static string JobState_printing {
            get {
                return ResourceManager.GetString("JobState_printing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string JobState_queued {
            get {
                return ResourceManager.GetString("JobState_queued", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sending.
        /// </summary>
        internal static string JobState_sending {
            get {
                return ResourceManager.GetString("JobState_sending", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to not set (open to the office network).
        /// </summary>
        internal static string PinNotSet {
            get {
                return ResourceManager.GetString("PinNotSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to set.
        /// </summary>
        internal static string PinSet {
            get {
                return ResourceManager.GetString("PinSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        internal static string PrinterStatus_busy {
            get {
                return ResourceManager.GetString("PrinterStatus_busy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string PrinterStatus_error {
            get {
                return ResourceManager.GetString("PrinterStatus_error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string PrinterStatus_offline {
            get {
                return ResourceManager.GetString("PrinterStatus_offline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paper out.
        /// </summary>
        internal static string PrinterStatus_paper_out {
            get {
                return ResourceManager.GetString("PrinterStatus_paper_out", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string PrinterStatus_paused {
            get {
                return ResourceManager.GetString("PrinterStatus_paused", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string PrinterStatus_ready {
            get {
                return ResourceManager.GetString("PrinterStatus_ready", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string PrinterStatus_unknown {
            get {
                return ResourceManager.GetString("PrinterStatus_unknown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings file: {0}.
        /// </summary>
        internal static string SettingsConfigFile {
            get {
                return ResourceManager.GetString("SettingsConfigFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to These settings are read from the file shown below. Changing them from this screen comes in a later u [rest of string was truncated].
        /// </summary>
        internal static string SettingsIntro {
            get {
                return ResourceManager.GetString("SettingsIntro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keep sent files for: {0} hour(s).
        /// </summary>
        internal static string SettingsKeepFiles {
            get {
                return ResourceManager.GetString("SettingsKeepFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shared PIN: {0}.
        /// </summary>
        internal static string SettingsPin {
            get {
                return ResourceManager.GetString("SettingsPin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Discovery port (UDP): {0}     Job port (TCP): {1}.
        /// </summary>
        internal static string SettingsPorts {
            get {
                return ResourceManager.GetString("SettingsPorts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sharing my printers: {0}.
        /// </summary>
        internal static string SettingsSharing {
            get {
                return ResourceManager.GetString("SettingsSharing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start with Windows: {0}.
        /// </summary>
        internal static string SettingsStartWithWindows {
            get {
                return ResourceManager.GetString("SettingsStartWithWindows", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Friendly name.
        /// </summary>
        internal static string ShareColFriendly {
            get {
                return ResourceManager.GetString("ShareColFriendly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        internal static string ShareColPrinter {
            get {
                return ResourceManager.GetString("ShareColPrinter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string ShareColShare {
            get {
                return ResourceManager.GetString("ShareColShare", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ShareColStatus {
            get {
                return ResourceManager.GetString("ShareColStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tick each printer you want other PCs to use. The friendly name is what people on the other PCs will  [rest of string was truncated].
        /// </summary>
        internal static string ShareIntro {
            get {
                return ResourceManager.GetString("ShareIntro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Jobs printed today: {0}.
        /// </summary>
        internal static string ShareJobsToday {
            get {
                return ResourceManager.GetString("ShareJobsToday", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reading the printer list....
        /// </summary>
        internal static string ShareLoading {
            get {
                return ResourceManager.GetString("ShareLoading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No printers are installed on this PC. Install the printer in Windows first, then press Refresh..
        /// </summary>
        internal static string ShareNoPrinters {
            get {
                return ResourceManager.GetString("ShareNoPrinters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not read the printer list: {0}.
        /// </summary>
        internal static string SharePrintersError {
            get {
                return ResourceManager.GetString("SharePrintersError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recent jobs received from other PCs.
        /// </summary>
        internal static string ShareRecentJobs {
            get {
                return ResourceManager.GetString("ShareRecentJobs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string ShareRefresh {
            get {
                return ResourceManager.GetString("ShareRefresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sharing is OFF. Other PCs cannot print here..
        /// </summary>
        internal static string ShareStatusOff {
            get {
                return ResourceManager.GetString("ShareStatusOff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sharing is ON. Other PCs can send print jobs to this PC on port {0}..
        /// </summary>
        internal static string ShareStatusOn {
            get {
                return ResourceManager.GetString("ShareStatusOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share the ticked printers with the office.
        /// </summary>
        internal static string ShareToggle {
            get {
                return ResourceManager.GetString("ShareToggle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PrintVect could not open port {0} for incoming print jobs. Another program (or a second copy of Prin [rest of string was truncated].
        /// </summary>
        internal static string SharingPortError {
            get {
                return ResourceManager.GetString("SharingPortError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your change could not be saved to {0}, so it will be lost when PrintVect closes. Ask the person who  [rest of string was truncated].
        /// </summary>
        internal static string SharingSaveError {
            get {
                return ResourceManager.GetString("SharingSaveError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PrintVect could not start sharing: {0}.
        /// </summary>
        internal static string SharingStartError {
            get {
                return ResourceManager.GetString("SharingStartError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PrintVect could not create its data folder: {0}  {1}  Ask the person who installed PrintVect to chec [rest of string was truncated].
        /// </summary>
        internal static string StartupFolderError {
            get {
                return ResourceManager.GetString("StartupFolderError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sharing is OFF.
        /// </summary>
        internal static string StatusSharingOff {
            get {
                return ResourceManager.GetString("StatusSharingOff", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sharing is ON.
        /// </summary>
        internal static string StatusSharingOn {
            get {
                return ResourceManager.GetString("StatusSharingOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string StatusVersion {
            get {
                return ResourceManager.GetString("StatusVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        internal static string TabDiagnostics {
            get {
                return ResourceManager.GetString("TabDiagnostics", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share my printers.
        /// </summary>
        internal static string TabShare {
            get {
                return ResourceManager.GetString("TabShare", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use shared printers.
        /// </summary>
        internal static string TabUse {
            get {
                return ResourceManager.GetString("TabUse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string TrayExit {
            get {
                return ResourceManager.GetString("TrayExit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open PrintVect.
        /// </summary>
        internal static string TrayOpen {
            get {
                return ResourceManager.GetString("TrayOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PrintVect keeps running in the tray so that printing keeps working. To close it completely, right-cl [rest of string was truncated].
        /// </summary>
        internal static string TrayStillRunningText {
            get {
                return ResourceManager.GetString("TrayStillRunningText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PrintVect is still running.
        /// </summary>
        internal static string TrayStillRunningTitle {
            get {
                return ResourceManager.GetString("TrayStillRunningTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Something went wrong inside PrintVect. The details have been written to the log file. If it happens  [rest of string was truncated].
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add to this PC.
        /// </summary>
        internal static string UseAdd {
            get {
                return ResourceManager.GetString("UseAdd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The printer could not be added. {0}.
        /// </summary>
        internal static string UseAddFailed {
            get {
                return ResourceManager.GetString("UseAddFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "{0}" is ready. Print to it from any program; the pages come out on {1}..
        /// </summary>
        internal static string UseAdded {
            get {
                return ResourceManager.GetString("UseAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creating "{0}" on this PC. If Windows asks for permission, choose Yes..
        /// </summary>
        internal static string UseAdding {
            get {
                return ResourceManager.GetString("UseAdding", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "{0}" is already on this PC..
        /// </summary>
        internal static string UseAlreadyAdded {
            get {
                return ResourceManager.GetString("UseAlreadyAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string UseColAddress {
            get {
                return ResourceManager.GetString("UseColAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Host PC.
        /// </summary>
        internal static string UseColHost {
            get {
                return ResourceManager.GetString("UseColHost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Printer on this PC.
        /// </summary>
        internal static string UseColLocalPrinter {
            get {
                return ResourceManager.GetString("UseColLocalPrinter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        internal static string UseColPrinter {
            get {
                return ResourceManager.GetString("UseColPrinter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string UseColStatus {
            get {
                return ResourceManager.GetString("UseColStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Waiting jobs.
        /// </summary>
        internal static string UseColWaiting {
            get {
                return ResourceManager.GetString("UseColWaiting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} shares {1} printer(s):.
        /// </summary>
        internal static string UseFoundPrinters {
            get {
                return ResourceManager.GetString("UseFoundPrinters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PC name or IP address:.
        /// </summary>
        internal static string UseHostLabel {
            get {
                return ResourceManager.GetString("UseHostLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use a printer that another PC in the office shares. Type that PC's name or IP address, press Look up [rest of string was truncated].
        /// </summary>
        internal static string UseIntro {
            get {
                return ResourceManager.GetString("UseIntro", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Printed today: {0}.
        /// </summary>
        internal static string UseJobsToday {
            get {
                return ResourceManager.GetString("UseJobsToday", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Asking {0}....
        /// </summary>
        internal static string UseLookingUp {
            get {
                return ResourceManager.GetString("UseLookingUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Look up.
        /// </summary>
        internal static string UseLookup {
            get {
                return ResourceManager.GetString("UseLookup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string UseLookupFailed {
            get {
                return ResourceManager.GetString("UseLookupFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Printers from other PCs on this PC:.
        /// </summary>
        internal static string UseMyPrinters {
            get {
                return ResourceManager.GetString("UseMyPrinters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} shares no printers. On that PC, open PrintVect, tick a printer and turn sharing ON..
        /// </summary>
        internal static string UseNoPrintersShared {
            get {
                return ResourceManager.GetString("UseNoPrintersShared", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No printer from another PC has been added yet..
        /// </summary>
        internal static string UseNoRemotePrinters {
            get {
                return ResourceManager.GetString("UseNoRemotePrinters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No jobs are waiting for "{0}"..
        /// </summary>
        internal static string UseNothingWaiting {
            get {
                return ResourceManager.GetString("UseNothingWaiting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Jobs sent from this PC:.
        /// </summary>
        internal static string UseRecentJobs {
            get {
                return ResourceManager.GetString("UseRecentJobs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string UseRemove {
            get {
                return ResourceManager.GetString("UseRemove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove "{0}" from this PC? Windows asks for permission..
        /// </summary>
        internal static string UseRemoveConfirm {
            get {
                return ResourceManager.GetString("UseRemoveConfirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The printer could not be removed. {0}.
        /// </summary>
        internal static string UseRemoveFailed {
            get {
                return ResourceManager.GetString("UseRemoveFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "{0}" was removed from this PC..
        /// </summary>
        internal static string UseRemoved {
            get {
                return ResourceManager.GetString("UseRemoved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} waiting job(s) are being sent again..
        /// </summary>
        internal static string UseRetried {
            get {
                return ResourceManager.GetString("UseRetried", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retry waiting jobs.
        /// </summary>
        internal static string UseRetry {
            get {
                return ResourceManager.GetString("UseRetry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose a printer in the list first..
        /// </summary>
        internal static string UseSelectFound {
            get {
                return ResourceManager.GetString("UseSelectFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose one of your printers first..
        /// </summary>
        internal static string UseSelectMine {
            get {
                return ResourceManager.GetString("UseSelectMine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send test page.
        /// </summary>
        internal static string UseTestPage {
            get {
                return ResourceManager.GetString("UseTestPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The test page {0} is missing. Copy the whole PrintVect folder again..
        /// </summary>
        internal static string UseTestPageMissing {
            get {
                return ResourceManager.GetString("UseTestPageMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The test page was handed to "{0}"; watch the job list below..
        /// </summary>
        internal static string UseTestPageSent {
            get {
                return ResourceManager.GetString("UseTestPageSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "{0}" cannot be watched for jobs: {1}.
        /// </summary>
        internal static string UseWatcherError {
            get {
                return ResourceManager.GetString("UseWatcherError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
