#!/usr/bin/env python3
"""Regenerates src/PrintVect.App/Strings.Designer.cs from Strings.resx.

Visual Studio does this automatically (ResXFileCodeGenerator). This script does the same
for people who edit Strings.resx without Visual Studio. Run it from the repo root:

    python3 tools/generate_strings.py
"""
import os
import sys
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESX = os.path.join(ROOT, "src", "PrintVect.App", "Strings.resx")
OUT = os.path.join(ROOT, "src", "PrintVect.App", "Strings.Designer.cs")

HEADER = '''//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool (tools/generate_strings.py or Visual Studio).
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. Edit Strings.resx instead.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintVect.App {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintVect.App.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
'''

FOOTER = '''    }
}
'''

PROPERTY = '''
        /// <summary>
        ///   Looks up a localized string similar to {summary}.
        /// </summary>
        internal static string {name} {{
            get {{
                return ResourceManager.GetString("{name}", resourceCulture);
            }}
        }}
'''


def main():
    tree = ET.parse(RESX)
    entries = []
    for data in tree.getroot().findall("data"):
        name = data.get("name")
        value = (data.findtext("value") or "")
        entries.append((name, value))
    entries.sort(key=lambda e: e[0])

    parts = [HEADER]
    for name, value in entries:
        summary = value.replace("\r", "").replace("\n", " ").strip()
        if len(summary) > 100:
            summary = summary[:100] + " [rest of string was truncated]"
        summary = summary.replace("*/", "* /").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        parts.append(PROPERTY.format(name=name, summary=summary))
    parts.append(FOOTER)

    text = "".join(parts).replace("\n", "\r\n")
    with open(OUT, "w", encoding="utf-8", newline="") as f:
        f.write(text)
    print("wrote %s (%d strings)" % (os.path.relpath(OUT, ROOT), len(entries)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
